### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#116]
Maybe we could use one for the coming release :
https://github.com/marketplace/actions/changelog-ci

...

**Comment by SebSept** [comment]
I m working this + the release workflow ..

**Comment by okom3pom** [comment]
Si on merge dans la dev dans master tu penses que les PR de dev ne seront pas prit en compte ?

Je l'utilise sur un module

**Comment by SebSept** [comment]
Le pr reste en place. 
C'est juste une info un pr.
J'ai peut être pas compris la question ..

J'ai utilise release drafter par ailleurs, c'est pas très compliqué, faut juste faire pas oublié qu'il va chercher sa config dans la branche par défaut du repo. Donc faudra intégrer ce workflow directement dans master 

As tu utilisé, le wf changelog ?

**Comment by okom3pom** [comment]
Ma question était pour ce que tu as écris plus haut : 

_but I suppose it should be in place at the start of the changes because it gather changes as they are merged._

Je pense que si on ajoute release-drafter.yml ( config ) dans la dev et qu'on ajoute le workflow dans master ça passe.

Quand on mergera la dev dans master on aura le changelog dans le draft.

Genre :

![Capture d’écran de 2021-05-27 12-54-30](https://user-images.githubusercontent.com/5064590/119814577-da5bb500-beea-11eb-89c6-4ddc3aa45c46.png)

**Comment by SebSept** [comment]
Oui, contrairement à ce que je croyais, le texte généré par release drafter va chercher tout les Pr merges depuis la dernière release. Donc on peut l'intégrer juste avant de release.

I was wrong, release-drafter gather all merged pr since last release.

**Comment by SebSept** [comment]
> Je pense que si on ajoute release-drafter.yml ( config ) dans la dev et qu'on ajoute le workflow dans dev aussi ça passe

Et bien non justement, j'ai passé une bonne heure avant de capter ça.
