### ISSUE TITLE
Add phpstan check to the github action

### ISSUE THREAD

**Issue by zalexki** [friends-of-presta/fop_console#7]

**Comment by SebSept** [comment]
# phpstan workflow PR choice

Both Pull Requests runs phpstan on github after a push or pull request.

There is 2 versions :
one à la Prestashop : with docker, prestashop installed : #79
one à la Seb : without docker, source code just unzipped  : #80

Which one do you prefer ? Why ?

Here is a list to compare (can be improved).

## #80 (without docker, source code just unzipped)

⬆️ :
- simpler
- faster
- less dependencies (more robust)
- easy to modify/test at home

⬇️ :
- it diverges from Prestashop way 
- is not ready to run integration tests (guessed)
- easier maintenance (just copy what Prestashop will implement)

## #78 (with docker and prestashop installed): the exact opposite of previous list

⬆️ :
- follow the Prestashop way 
- ready to run integration tests (I guess) 
- easier maintenance (just copy what Prestashop will implement)  

⬇️ :
- more complex (github action, docker image)
- slower (because of docker)
- more dependencies (docker, docker images (managed by prestashop))
- not easy to modify (requires docker knowledge)


Vote for 80 (Seb implementation) : 🎉 
Vote for 79 (Prestashop implementation) : 🚀

**Comment by SebSept** [comment]
I voted for my implementation 😄 .
The possibility to easily modify the workflow, the less dependencies are really good points.
Being dependent on docker, dockerhub and prestashop managed images for only potential benefits (no real benefits, only potential) makes me vote for #80

**Comment by webrdinfo** [comment]
vote for #80 For the same reasons of SebSept

**Comment by jf-viguier** [comment]
I vote for #80 for simplicity

**Comment by PrestaSafe** [comment]
I can't really judge, i vote for simplicity too. So #80
