### ISSUE TITLE
Support php 5.6 & 7.0

### ISSUE THREAD

**Issue by jf-viguier** [friends-of-presta/fop_console#76]
Actually, there is and error "Your Composer dependencies require a PHP version ">= 7.1.0""
We should support same php version as prestashop 1.7.5+

**Comment by nenes25** [comment]
As discussed on this topic, i don't know if we should support these versions.
This will cause a lot of work and trouble to keep compatibility instead on working on new features.
ping @friends-of-presta/core-friends WDYT ?

**Comment by SebSept** [comment]
The idea to support php 5.6, 7.0, 7.1 is fair. In fact, it sounds like a problem for me.
It implies to code for php 5.6 and then adapt to run on higher versions. (I don't think we can code for php 7.2 then adapt for lower version, that's a guess).
That means losing the benefits introduced by php since php 7.x  (typed return types, scalar typed arguments for example)
That also implies a significant amount of work. Do we have the resource for that ? I'm pretty sure we don't.

Prestashop supports php 5.6 for backward compatibility. I guess they feel it as a constraint, not a feature.
Nothing forces us to support php under 7.2. Let's not add ourselves unnecessary constraints just because it looks logic.

**My opinion is to support php 7.2+, nothing under that version.**

Personally, I've found a great way to improve my coding by participating to this project. (and other out of scope positive things)
Getting locked to a php version that ended it's life 2 years ago will strongly decrease my attractiveness to this project ( to put it mildly / pour ne pas dire plus).

**Comment by nenes25** [comment]
@jf-viguier  @SebSept  is still something to do with this issue ? Or can we close it ?

**Comment by SebSept** [comment]
I had a look in composer.lock also.
I think every thing is ok.
You can close it.
